const rules = [
  { from: "^/streams/1$", to: "/streams/crojayn", statusCode: 301 },
  { from: "^/streams/2$", to: "/streams/ruby-and-the-night-hawks", statusCode: 301 },
  { from: "^/streams/3$", to: "/streams/tootawl", statusCode: 301 },
  { from: "^/streams/4$", to: "/streams/the-band-anna", statusCode: 301 },
  { from: "^/streams/5$", to: "/streams/sarah-beth", statusCode: 301 },
  { from: "^/streams/6$", to: "/streams/mb-soul-review", statusCode: 301 },
  { from: "^/streams/7$", to: "/streams/psychedelic-pill", statusCode: 301 },
  { from: "^/streams/8$", to: "/streams/dan-o-keeffe-and-band", statusCode: 301 },
  { from: "^/streams/9$", to: "/streams/rowan", statusCode: 301 },
  { from: "^/streams/10$", to: "/streams/mongoose", statusCode: 301 },
  { from: "^/streams/11$", to: "/streams/rhythm-company", statusCode: 301 },
  { from: "^/streams/12$", to: "/streams/goosefat", statusCode: 301 },
  { from: "^/streams/13$", to: "/streams/franklin", statusCode: 301 },
  { from: "^/streams/14$", to: "/streams/mide-houlihan", statusCode: 301 },
  { from: "^/streams/15$", to: "/streams/ocd", statusCode: 301 },
  { from: "^/streams/16$", to: "/streams/sarah-beth-blackheart-and-tootawl", statusCode: 301 },
  { from: "^/streams/17$", to: "/streams/the-electronic-folk", statusCode: 301 },
  { from: "^/streams/18$", to: "/streams/rich-city-vultures", statusCode: 301 },
  { from: "^/streams/19$", to: "/streams/eve-clague", statusCode: 301 },
  { from: "^/streams/20$", to: "/streams/hank-wedel-living-in-the-land-of-love", statusCode: 301 },
  { from: "^/streams/21$", to: "/streams/voodoo-child", statusCode: 301 },
  { from: "^/streams/22$", to: "/streams/the-lost-gecko", statusCode: 301 },
  { from: "^/streams/23$", to: "/streams/stay", statusCode: 301 },
  { from: "^/streams/24$", to: "/streams/colin-andrew-trio", statusCode: 301 },
  { from: "^/streams/25$", to: "/streams/human-instinct", statusCode: 301 },
  { from: "^/streams/26$", to: "/streams/crab-seal-teeth", statusCode: 301 },
  { from: "^/streams/28$", to: "/streams/mrc", statusCode: 301 },
  { from: "^/streams/32$", to: "/streams/dry-roasted-peanuts-at-cyprus-ave", statusCode: 301 },
  { from: "^/streams/36$", to: "/streams/the-vestas", statusCode: 301 },
  { from: "^/streams/37$", to: "/streams/luki", statusCode: 301 },
  { from: "^/streams/39$", to: "/streams/musical-brotherhood", statusCode: 301 },
  { from: "^/streams/40$", to: "/streams/ruby-and-the-night-hawks-vp", statusCode: 301 },
  { from: "^/streams/41$", to: "/streams/dry-roasted-peanuts-feature", statusCode: 301 },
  { from: "^/streams/43$", to: "/streams/don-baker-and-rob-strong-feature", statusCode: 301 },
  { from: "^/streams/44$", to: "/streams/horse-at-an-spailpin-fanach", statusCode: 301 },
  { from: "^/streams/45$", to: "/streams/cork-and-wigan-jazz-twinning-event", statusCode: 301 },
  { from: "^/streams/46$", to: "/streams/don-baker-winner-in-you", statusCode: 301 },
  { from: "^/streams/47$", to: "/streams/quangodelic-the-funk-marches-on", statusCode: 301 },
  { from: "^/streams/48$", to: "/streams/don-baker-and-rob-strong-shoe-shine-man", statusCode: 301 },
  { from: "^/streams/49$", to: "/streams/don-baker-and-rob-strong-keep-it-to-yourself", statusCode: 301 },
  { from: "^/streams/50$", to: "/streams/a-taste-of-quangodelic", statusCode: 301 },
  { from: "^/streams/51$", to: "/streams/going-underground", statusCode: 301 }
]

module.exports = rules