query paginatedStreams ($first: Int, $skip: Int) {
  streams (
    first: $first,
    skip: $skip,
    where: {
      status: PUBLISHED
    }
  ) {
    title
    slug
    venue
    venueUrl
    embed
    time
    description
    thumbnail {
      handle
    }
  }
}